version: "3.7"

networks:
    network-1:
        driver: bridge

services:
    order-api:
        hostname: order-api
        container_name: order-service-api
        build:
            context: .
            target: development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
        command: npm run start:dev
        env_file:
            - .env.dev
        depends_on:
            - mysql
        networks:
            - network-1
    mysql:
        container_name: order-service-db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3307:3306"
        networks:
            - network-1
        volumes:
            - order-service-db:/var/lib/mysql

# Names our volume
volumes:
    order-service-db:
